from __future__ import annotations

"""Regenerates colab/model_surgery_colab.ipynb."""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "colab" / "model_surgery_colab.ipynb"


def md(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": text}


def code(text: str) -> dict:
    return {"cell_type": "code", "metadata": {}, "execution_count": None, "outputs": [], "source": text}


def build_notebook() -> dict:
    cells = [
        md(
            "# Seam Harmonizer Model Surgery Colab\n\n"
            "Готовый notebook для запуска `model_surgery` на Colab GPU.\n\n"
            "Сценарий:\n"
            "- clone репозитория из git;\n"
            "- копирование `synthetic_triplets_500` с Google Drive в локальный диск или RAM;\n"
            "- копирование training checkpoints / runs локально, чтобы не читать их с Drive во время eval;\n"
            "- сборка runtime-конфига для `model_surgery`;\n"
            "- запуск `python -m model_surgery.run`;\n"
            "- синк результатов обратно на Drive."
        ),
        code(
            "# 0. PARAMS\n"
            "from pathlib import Path\n"
            "import os\n\n"
            "REPO_CLONE_URL = 'https://github.com/aaandreyev/unet_seam.git'\n"
            "REPO_CLONE_REF = 'main'\n"
            "PROJECT_ROOT = Path('/content/unet_seam')\n\n"
            "DRIVE_ROOT = Path('/content/drive/MyDrive/unet_seam_runs')\n"
            "DRIVE_TRIPLETS_DIR = DRIVE_ROOT / 'synthetic_triplets_500'\n"
            "DRIVE_TRIPLETS_ZIP = DRIVE_ROOT / 'synthetic_triplets_500.zip'\n"
            "DRIVE_RUNS_PARENT = DRIVE_ROOT\n"
            "DRIVE_SURGERY_ROOT = DRIVE_ROOT / 'model_surgery_runs'\n"
            "# Optional: if you keep loose checkpoints outside run folders, point this to that directory.\n"
            "# Leave as None when all checkpoints live under run_XXX/checkpoints.\n"
            "DRIVE_LOCAL_CHECKPOINTS_DIR = None\n"
            "RUN_NAME = 'surgery_run001'\n\n"
            "USE_RAMDISK = True\n"
            "RAMDISK_SIZE_GB = 8\n"
            "COPY_RUNS_LOCALLY = True\n"
            "COPY_CHECKPOINTS_LOCALLY = True\n"
            "COPY_EXISTING_SURGERY_OUTPUTS = True\n"
            "SYNC_INTERVAL_SEC = 180\n\n"
            "USE_SHARDED_TRIPLETS = True\n"
            "TRIPLET_SHARD_SIZE = 64\n"
            "STAGES = 's0,s1,s2,s3,s4,s5'\n"
            "TOP_K = 4\n"
            "MAX_CYCLES = 12\n"
            "TARGET_QUALITY_RELATIVE = 0.12\n"
            "MINI_STRIPS = 20\n"
            "FULL_STRIPS = 200\n"
            "EVAL_BATCH_SIZE = None  # None -> auto by GPU type\n"
            "EVAL_NUM_WORKERS = 4\n"
            "MATERIALIZED_PRELOAD = True\n"
            "ENABLE_FINETUNE_ON_PLATEAU = True\n"
            "FINETUNE_PLATEAU_CYCLES = 5\n"
            "FINETUNE_EPOCHS = 2\n"
            "FINETUNE_LR = 5e-6\n\n"
            "LOCAL_ROOT = Path('/content/ms_runtime')\n"
            "LOCAL_DATA_ROOT = LOCAL_ROOT / 'data'\n"
            "LOCAL_TRIPLETS_DIR = LOCAL_DATA_ROOT / 'synthetic_triplets_500'\n"
            "LOCAL_TRIPLETS_SHARDED_DIR = LOCAL_DATA_ROOT / 'synthetic_triplets_500_sharded'\n"
            "LOCAL_TRIPLETS_ZIP = DATA_BASE / 'synthetic_triplets_500.zip' if 'DATA_BASE' in globals() else LOCAL_DATA_ROOT / 'synthetic_triplets_500.zip'\n"
            "LOCAL_OUTPUTS_ROOT = PROJECT_ROOT / 'outputs'\n"
            "LOCAL_RUNS_DIR = LOCAL_OUTPUTS_ROOT / 'unet_seam_runs'\n"
            "LOCAL_CHECKPOINTS_DIR = LOCAL_OUTPUTS_ROOT / 'checkpoints'\n"
            "LOCAL_SURGERY_OUTPUT_DIR = PROJECT_ROOT / 'model_surgery' / 'outputs_colab'\n"
            "LOCAL_SURGERY_CFG = PROJECT_ROOT / 'runtime_configs' / 'model_surgery_colab.yaml'\n"
            "DRIVE_RUN_DIR = DRIVE_SURGERY_ROOT / RUN_NAME\n"
            "DRIVE_SURGERY_OUTPUT_DIR = DRIVE_RUN_DIR / 'model_surgery_outputs'\n"
        ),
        code(
            "# 1. MOUNT DRIVE\n"
            "from google.colab import drive\n"
            "drive.mount('/content/drive')\n"
            "print('Drive mounted')\n"
        ),
        code(
            "# 2. INSTALL / RUNTIME CHECKS\n"
            "import json, platform, subprocess, sys\n"
            "pkgs = ['pyyaml', 'tqdm', 'psutil', 'scikit-image', 'scipy', 'lpips', 'safetensors']\n"
            "subprocess.run(['apt-get', 'update', '-qq'], check=False)\n"
            "subprocess.run(['apt-get', 'install', '-y', '-qq', 'pigz'], check=False)\n"
            "subprocess.run([sys.executable, '-m', 'pip', 'install', '-q'] + pkgs, check=True)\n"
            "import torch\n"
            "gpu_name = torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'cpu'\n"
            "print(json.dumps({\n"
            "    'python': sys.executable,\n"
            "    'platform': platform.platform(),\n"
            "    'torch': torch.__version__,\n"
            "    'cuda': torch.cuda.is_available(),\n"
            "    'gpu_name': gpu_name,\n"
            "}, ensure_ascii=False))\n"
            "if EVAL_BATCH_SIZE is None:\n"
            "    name = gpu_name.upper()\n"
            "    if 'A100' in name:\n"
            "        EVAL_BATCH_SIZE = 48\n"
            "    elif 'L4' in name:\n"
            "        EVAL_BATCH_SIZE = 24\n"
            "    elif 'T4' in name:\n"
            "        EVAL_BATCH_SIZE = 8\n"
            "    else:\n"
            "        EVAL_BATCH_SIZE = 8\n"
            "print('EVAL_BATCH_SIZE =', EVAL_BATCH_SIZE)\n"
        ),
        code(
            "# 3. OPTIONAL RAMDISK\n"
            "import os, psutil, shutil, subprocess\n"
            "RAM_ROOT = Path('/content/ramdisk')\n"
            "if USE_RAMDISK:\n"
            "    mem = psutil.virtual_memory()\n"
            "    avail_gb = int(mem.available / (1024 ** 3))\n"
            "    eff = min(RAMDISK_SIZE_GB, max(4, avail_gb - 24))\n"
            "    RAM_ROOT.mkdir(parents=True, exist_ok=True)\n"
            "    mounted = subprocess.run(['mountpoint', str(RAM_ROOT)], capture_output=True).returncode == 0\n"
            "    if not mounted:\n"
            "        mount_result = subprocess.run(\n"
            "            ['mount', '-t', 'tmpfs', '-o', f'size={eff}G,mode=777', 'tmpfs', str(RAM_ROOT)],\n"
            "            text=True, capture_output=True,\n"
            "        )\n"
            "        if mount_result.returncode != 0:\n"
            "            print('RAMDISK mount failed; fallback to /content:', mount_result.stderr[-500:])\n"
            "            USE_RAMDISK = False\n"
            "        else:\n"
            "            print(f'Ramdisk mounted: {eff} GB at {RAM_ROOT}')\n"
            "DATA_BASE = (RAM_ROOT / 'data') if USE_RAMDISK else LOCAL_DATA_ROOT\n"
            "DATA_BASE.mkdir(parents=True, exist_ok=True)\n"
            "LOCAL_TRIPLETS_DIR = DATA_BASE / 'synthetic_triplets_500'\n"
            "LOCAL_TRIPLETS_ZIP = DATA_BASE / 'synthetic_triplets_500.zip'\n"
            "for p in [LOCAL_OUTPUTS_ROOT, LOCAL_RUNS_DIR, LOCAL_CHECKPOINTS_DIR, LOCAL_SURGERY_OUTPUT_DIR, LOCAL_SURGERY_CFG.parent]:\n"
            "    p.mkdir(parents=True, exist_ok=True)\n"
            "print('LOCAL_TRIPLETS_DIR =', LOCAL_TRIPLETS_DIR)\n"
        ),
        code(
            "# 4. CLONE REPOSITORY\n"
            "import shutil, subprocess, sys\n"
            "if PROJECT_ROOT.exists():\n"
            "    shutil.rmtree(PROJECT_ROOT)\n"
            "subprocess.run([\n"
            "    'git', 'clone', '--depth', '1', '-b', REPO_CLONE_REF, REPO_CLONE_URL, str(PROJECT_ROOT)\n"
            "], check=True)\n"
            "sys.path.insert(0, str(PROJECT_ROOT))\n"
            "print('PROJECT_ROOT =', PROJECT_ROOT)\n"
        ),
        code(
            "# 5. PREPARE TRIPLETS + COPY RUNS / CHECKPOINTS / PREVIOUS OUTPUTS LOCALLY\n"
            "import os, shutil, time, zipfile\n"
            "from concurrent.futures import ThreadPoolExecutor\n"
            "from tqdm.auto import tqdm\n\n"
            "def _copy_file(args):\n"
            "    src, dst = args\n"
            "    dst.parent.mkdir(parents=True, exist_ok=True)\n"
            "    shutil.copy2(src, dst)\n"
            "    return src.stat().st_size\n\n"
            "def copy_tree(src: Path, dst: Path, workers: int = 8, wipe: bool = True) -> None:\n"
            "    if not src.exists():\n"
            "        raise FileNotFoundError(src)\n"
            "    if wipe and dst.exists():\n"
            "        shutil.rmtree(dst)\n"
            "    dst.mkdir(parents=True, exist_ok=True)\n"
            "    files = [p for p in src.rglob('*') if p.is_file()]\n"
            "    total = sum(p.stat().st_size for p in files)\n"
            "    with ThreadPoolExecutor(max_workers=max(1, min(workers, len(files) or 1))) as ex:\n"
            "        it = ex.map(_copy_file, ((p, dst / p.relative_to(src)) for p in files), chunksize=8)\n"
            "        copied = 0\n"
            "        with tqdm(total=total, unit='B', unit_scale=True, desc=f'copy {src.name}') as pbar:\n"
            "            for n in it:\n"
            "                copied += n\n"
            "                pbar.update(n)\n\n"
            "def unzip_tree(zip_path: Path, dst: Path) -> None:\n"
            "    if not zip_path.exists():\n"
            "        raise FileNotFoundError(zip_path)\n"
            "    if dst.exists():\n"
            "        shutil.rmtree(dst)\n"
            "    dst.mkdir(parents=True, exist_ok=True)\n"
            "    with zipfile.ZipFile(zip_path, 'r') as zf:\n"
            "        members = [m for m in zf.infolist() if not m.is_dir()]\n"
            "        root = dst.resolve()\n"
            "        total = sum(m.file_size for m in members)\n"
            "        with tqdm(total=total, unit='B', unit_scale=True, desc=f'unzip {zip_path.name}') as pbar:\n"
            "            for member in members:\n"
            "                out_path = (dst / member.filename).resolve()\n"
            "                try:\n"
            "                    out_path.relative_to(root)\n"
            "                except ValueError as exc:\n"
            "                    raise RuntimeError(f'Unsafe zip entry: {member.filename!r}') from exc\n"
            "                out_path.parent.mkdir(parents=True, exist_ok=True)\n"
            "                with zf.open(member, 'r') as src_f, out_path.open('wb') as dst_f:\n"
            "                    while True:\n"
            "                        chunk = src_f.read(8 * 1024 * 1024)\n"
            "                        if not chunk:\n"
            "                            break\n"
            "                        dst_f.write(chunk)\n"
            "                        pbar.update(len(chunk))\n\n"
            "if DRIVE_TRIPLETS_DIR.exists():\n"
            "    copy_tree(DRIVE_TRIPLETS_DIR, LOCAL_TRIPLETS_DIR, workers=8, wipe=True)\n"
            "elif DRIVE_TRIPLETS_ZIP.exists():\n"
            "    shutil.copy2(DRIVE_TRIPLETS_ZIP, LOCAL_TRIPLETS_ZIP)\n"
            "    unzip_tree(LOCAL_TRIPLETS_ZIP, LOCAL_TRIPLETS_DIR)\n"
            "    nested = LOCAL_TRIPLETS_DIR / 'synthetic_triplets_500'\n"
            "    if nested.exists() and (nested / 'manifest.jsonl').exists() and not (LOCAL_TRIPLETS_DIR / 'manifest.jsonl').exists():\n"
            "        tmp_dst = LOCAL_TRIPLETS_DIR.with_name(LOCAL_TRIPLETS_DIR.name + '_tmp')\n"
            "        if tmp_dst.exists():\n"
            "            shutil.rmtree(tmp_dst)\n"
            "        nested.rename(tmp_dst)\n"
            "        shutil.rmtree(LOCAL_TRIPLETS_DIR)\n"
            "        tmp_dst.rename(LOCAL_TRIPLETS_DIR)\n"
            "else:\n"
            "    raise FileNotFoundError(f'Neither {DRIVE_TRIPLETS_DIR} nor {DRIVE_TRIPLETS_ZIP} exists')\n"
            "if not (LOCAL_TRIPLETS_DIR / 'manifest.jsonl').exists():\n"
            "    raise FileNotFoundError(LOCAL_TRIPLETS_DIR / 'manifest.jsonl')\n"
            "if COPY_RUNS_LOCALLY and DRIVE_RUNS_PARENT.exists():\n"
            "    for run_dir in sorted(DRIVE_RUNS_PARENT.iterdir()):\n"
            "        if not run_dir.is_dir():\n"
            "            continue\n"
            "        if run_dir.name in {'synthetic_triplets_500', 'model_surgery_runs'}:\n"
            "            continue\n"
            "        if not (run_dir / 'checkpoints').exists():\n"
            "            continue\n"
            "        copy_tree(run_dir, LOCAL_RUNS_DIR / run_dir.name, workers=8, wipe=True)\n"
            "if COPY_CHECKPOINTS_LOCALLY and DRIVE_LOCAL_CHECKPOINTS_DIR is not None and DRIVE_LOCAL_CHECKPOINTS_DIR.exists():\n"
            "    copy_tree(DRIVE_LOCAL_CHECKPOINTS_DIR, LOCAL_CHECKPOINTS_DIR, workers=8, wipe=True)\n"
            "if COPY_EXISTING_SURGERY_OUTPUTS and DRIVE_SURGERY_OUTPUT_DIR.exists():\n"
            "    copy_tree(DRIVE_SURGERY_OUTPUT_DIR, LOCAL_SURGERY_OUTPUT_DIR, workers=8, wipe=False)\n"
            "print('triplets:', LOCAL_TRIPLETS_DIR)\n"
            "print('runs:', LOCAL_RUNS_DIR)\n"
            "print('checkpoints:', LOCAL_CHECKPOINTS_DIR)\n"
            "print('surgery outputs:', LOCAL_SURGERY_OUTPUT_DIR)\n"
        ),
        code(
            "# 6. OPTIONAL REPACK TO SHARDED TRIPLETS + BUILD RUNTIME CONFIG FOR MODEL SURGERY\n"
            "import subprocess, sys, yaml\n"
            "MATERIALIZED_DIR_FOR_SURGERY = LOCAL_TRIPLETS_DIR\n"
            "if USE_SHARDED_TRIPLETS:\n"
            "    manifest_text = (LOCAL_TRIPLETS_DIR / 'manifest.jsonl').read_text(encoding='utf-8')\n"
            "    if '\"shard_path\"' not in manifest_text[:4000] and 'shard_path' not in manifest_text[:4000]:\n"
            "        subprocess.run([\n"
            "            sys.executable, '-m', 'scripts.repack_materialized_triplets_to_shards',\n"
            "            '--src', str(LOCAL_TRIPLETS_DIR),\n"
            "            '--out', str(LOCAL_TRIPLETS_SHARDED_DIR),\n"
            "            '--shard-size', str(TRIPLET_SHARD_SIZE),\n"
            "            '--overwrite',\n"
            "        ], cwd=str(PROJECT_ROOT), check=True)\n"
            "        MATERIALIZED_DIR_FOR_SURGERY = LOCAL_TRIPLETS_SHARDED_DIR\n"
            "    else:\n"
            "        MATERIALIZED_DIR_FOR_SURGERY = LOCAL_TRIPLETS_DIR\n"
            "print('MATERIALIZED_DIR_FOR_SURGERY =', MATERIALIZED_DIR_FOR_SURGERY)\n"
            "cfg_path = PROJECT_ROOT / 'model_surgery' / 'config.yaml'\n"
            "cfg = yaml.safe_load(cfg_path.read_text(encoding='utf-8'))\n"
            "cfg['runs_dir'] = str(LOCAL_RUNS_DIR)\n"
            "cfg['local_checkpoints_dir'] = str(LOCAL_CHECKPOINTS_DIR)\n"
            "cfg['manifest'] = str(PROJECT_ROOT / 'manifests' / 'input_raw_manifest.jsonl')\n"
            "cfg['output_dir'] = str(LOCAL_SURGERY_OUTPUT_DIR)\n"
            "cfg['target_quality_relative'] = float(TARGET_QUALITY_RELATIVE)\n"
            "cfg['eval']['materialized_dir'] = str(MATERIALIZED_DIR_FOR_SURGERY)\n"
            "cfg['eval']['mini_strips'] = int(MINI_STRIPS)\n"
            "cfg['eval']['full_strips'] = int(FULL_STRIPS)\n"
            "cfg['eval']['batch_size'] = int(EVAL_BATCH_SIZE)\n"
            "cfg['eval']['num_workers'] = int(EVAL_NUM_WORKERS)\n"
            "cfg['eval']['materialized_preload'] = bool(MATERIALIZED_PRELOAD)\n"
            "cfg['s5_cycle']['max_cycles'] = int(MAX_CYCLES)\n"
            "cfg['s5_cycle']['top_k_base'] = int(TOP_K)\n"
            "cfg['s5_cycle']['finetune_on_plateau']['enabled'] = bool(ENABLE_FINETUNE_ON_PLATEAU)\n"
            "cfg['s5_cycle']['finetune_on_plateau']['plateau_cycles'] = int(FINETUNE_PLATEAU_CYCLES)\n"
            "cfg['s5_cycle']['finetune_on_plateau']['epochs'] = int(FINETUNE_EPOCHS)\n"
            "cfg['s5_cycle']['finetune_on_plateau']['lr'] = float(FINETUNE_LR)\n"
            "enabled_stages = {s.strip() for s in STAGES.split(',') if s.strip()}\n"
            "stage_map = {\n"
            "    's0_survey': 's0',\n"
            "    's1_gate_search': 's1',\n"
            "    's2_ablation': 's2',\n"
            "    's3_merge': 's3',\n"
            "    's4_surgery': 's4',\n"
            "    's5_cycle': 's5',\n"
            "}\n"
            "for key, short_name in stage_map.items():\n"
            "    cfg['stages'][key] = short_name in enabled_stages\n"
            "LOCAL_SURGERY_CFG.parent.mkdir(parents=True, exist_ok=True)\n"
            "LOCAL_SURGERY_CFG.write_text(yaml.safe_dump(cfg, sort_keys=False), encoding='utf-8')\n"
            "print('runtime config ->', LOCAL_SURGERY_CFG)\n"
        ),
        code(
            "# 7. BACKGROUND SYNC TO DRIVE\n"
            "import shutil, threading, time\n"
            "if 'SYNC_STOP' in globals():\n"
            "    SYNC_STOP.set()\n"
            "SYNC_STOP = threading.Event()\n"
            "DRIVE_SURGERY_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)\n"
            "def sync_tree(src: Path, dst: Path) -> int:\n"
            "    n = 0\n"
            "    if not src.exists():\n"
            "        return n\n"
            "    for path in src.rglob('*'):\n"
            "        if not path.is_file():\n"
            "            continue\n"
            "        rel = path.relative_to(src)\n"
            "        out = dst / rel\n"
            "        tmp = out.with_name(f'.{out.name}.tmp')\n"
            "        out.parent.mkdir(parents=True, exist_ok=True)\n"
            "        if not out.exists() or out.stat().st_size != path.stat().st_size or out.stat().st_mtime < path.stat().st_mtime:\n"
            "            shutil.copy2(path, tmp)\n"
            "            tmp.replace(out)\n"
            "            n += 1\n"
            "    return n\n"
            "def sync_all_to_drive():\n"
            "    n = sync_tree(LOCAL_SURGERY_OUTPUT_DIR, DRIVE_SURGERY_OUTPUT_DIR)\n"
            "    print('sync tick:', n, 'files ->', DRIVE_SURGERY_OUTPUT_DIR, flush=True)\n"
            "def _sync_loop():\n"
            "    while True:\n"
            "        sync_all_to_drive()\n"
            "        if SYNC_STOP.wait(SYNC_INTERVAL_SEC):\n"
            "            break\n"
            "sync_all_to_drive()\n"
            "sync_thread = threading.Thread(target=_sync_loop, daemon=True)\n"
            "sync_thread.start()\n"
            "print('background sync started')\n"
        ),
        code(
            "# 8. RUN MODEL SURGERY\n"
            "import os, subprocess, sys, threading\n"
            "env = os.environ.copy()\n"
            "env['PYTHONPATH'] = str(PROJECT_ROOT)\n"
            "env['PYTHONUNBUFFERED'] = '1'\n"
            "env.setdefault('PYTORCH_CUDA_ALLOC_CONF', 'expandable_segments:True')\n"
            "cmd = [\n"
            "    sys.executable, '-u', '-m', 'model_surgery.run',\n"
            "    '--config', str(LOCAL_SURGERY_CFG),\n"
            "    '--stages', STAGES,\n"
            "    '--top-k', str(TOP_K),\n"
            "    '--max-cycles', str(MAX_CYCLES),\n"
            "    '--output-dir', str(LOCAL_SURGERY_OUTPUT_DIR),\n"
            "]\n"
            "print('SURGERY CMD:', ' '.join(map(str, cmd)))\n"
            "def _stream_cmd(cmd, cwd, env):\n"
            "    p = subprocess.Popen(cmd, cwd=cwd, env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1)\n"
            "    def _pump():\n"
            "        if p.stdout is not None:\n"
            "            for line in p.stdout:\n"
            "                print(line, end='', flush=True)\n"
            "    t = threading.Thread(target=_pump, daemon=True)\n"
            "    t.start()\n"
            "    rc = p.wait()\n"
            "    t.join(timeout=30)\n"
            "    if rc != 0:\n"
            "        raise subprocess.CalledProcessError(rc, cmd)\n"
            "_stream_cmd(cmd, str(PROJECT_ROOT), env)\n"
        ),
        code(
            "# 9. FINAL SYNC + SUMMARY\n"
            "if 'SYNC_STOP' in globals():\n"
            "    SYNC_STOP.set()\n"
            "if 'sync_all_to_drive' in globals():\n"
            "    sync_all_to_drive()\n"
            "print('Drive output dir =', DRIVE_SURGERY_OUTPUT_DIR)\n"
            "print('Artifacts:')\n"
            "for path in sorted(DRIVE_SURGERY_OUTPUT_DIR.rglob('*')):\n"
            "    if path.is_file():\n"
            "        print(path.relative_to(DRIVE_SURGERY_OUTPUT_DIR))\n"
        ),
    ]
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.10"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(build_notebook(), ensure_ascii=False, indent=2), encoding="utf-8")
    print(OUT)


if __name__ == "__main__":
    main()
