from __future__ import annotations
"""Regenerates colab/seam_harmonizer_train_eval_colab.ipynb.

The checked-in notebook is maintained to match this builder; re-run
`python scripts/build_colab_training_notebook.py` only when you update
`build_notebook()` and want the ipynb on disk to reflect it.
"""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "colab" / "seam_harmonizer_train_eval_colab.ipynb"

def md(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": text}


def code(text: str) -> dict:
    return {"cell_type": "code", "metadata": {}, "execution_count": None, "outputs": [], "source": text}


def build_notebook() -> dict:
    cells = [
        md(
            "# Seam Harmonizer v1 Colab Notebook\n\n"
            "Готовый ноутбук для **training -> validation -> eval -> export -> verify reload**.\n\n"
            "Локально нужно заранее собрать training bundle через `scripts/build_final_training_bundle.py`, "
            "загрузить `.tar.gz` на Google Drive и указать путь в параметрах ниже."
        ),
        code(
            "# 0. PARAMS\n"
            "from pathlib import Path\n"
            "import os\n\n"
            "DATASET_BUNDLE_DRIVE_PATH = '/content/drive/MyDrive/unet_seam/seam_harmonizer_training_bundle.tar.gz'\n"
            "DRIVE_RUNS_DIR = '/content/drive/MyDrive/unet_seam_runs'\n"
            "RUN_NAME = 'seam_harmonizer_v1_run001'\n"
            "REPO_CLONE_URL = 'https://github.com/aaandreyev/unet_seam.git'\n"
            "REPO_CLONE_REF = 'main'\n"
            "RUNTIME_ZIP_URL = ''\n"
            "USE_RAMDISK = True\n"
            "RAMDISK_SIZE_GB = 48\n"
            "COPY_ARCHIVE_TO_RAM_FIRST = True\n"
            "SYNC_INTERVAL_SEC = 180\n"
            "# NAF first stage: B×(4×ch0)×H×W < 2^31; at 1024×256, batch <= 63. Default 32 for Colab.\n"
            "TRAIN_BATCH_SIZE = 32\n"
            "VAL_BATCH_SIZE = 32\n"
            "TRAIN_EPOCHS = 20\n"
            "# Colab VMs vary; too many workers often stalls Drive/RAM-backed datasets.\n"
            "TRAIN_NUM_WORKERS = min(4, os.cpu_count() or 2)\n"
            "PRIMARY_CHECKPOINT = 'best_harmonizer_quality.pt'\n"
            "PROJECT_ROOT = Path('/content/seam_runtime')\n"
            "LOCAL_OUTPUTS = PROJECT_ROOT / 'outputs'\n"
            "LOCAL_CHECKPOINTS = LOCAL_OUTPUTS / 'checkpoints'\n"
            "LOCAL_EVAL = LOCAL_OUTPUTS / 'eval_reports'\n"
            "LOCAL_EXPORTS = LOCAL_OUTPUTS / 'exports'\n"
            "LOCAL_LOGS = LOCAL_OUTPUTS / 'logs'\n"
            "LOCAL_DATA_ROOT = Path('/content/dataset_bundle')\n"
            "DRIVE_RUN_DIR = Path(DRIVE_RUNS_DIR) / RUN_NAME\n"
            "DRIVE_CKPT_DIR = DRIVE_RUN_DIR / 'checkpoints'\n"
            "DRIVE_EVAL_DIR = DRIVE_RUN_DIR / 'eval_reports'\n"
            "DRIVE_EXPORT_DIR = DRIVE_RUN_DIR / 'exports'\n"
            "DRIVE_LOG_DIR = DRIVE_RUN_DIR / 'logs'\n"
        ),
        code(
            "# 1. MOUNT DRIVE\n"
            "from google.colab import drive\n"
            "drive.mount('/content/drive')\n"
            "print('Drive mounted')\n"
        ),
        code(
            "# 2. INSTALL / RUNTIME CHECKS\n"
            "import os, sys, subprocess, importlib.util, platform, json\n"
            "pkgs = ['pyyaml','scipy','scikit-image','safetensors','tqdm','lpips','psutil']\n"
            "subprocess.run(['apt-get', 'update', '-qq'], check=False)\n"
            "subprocess.run(['apt-get', 'install', '-y', '-qq', 'pigz'], check=False)\n"
            "subprocess.run([sys.executable, '-m', 'pip', 'install', '-q'] + pkgs, check=True)\n"
            "import torch\n"
            "device = 'cuda' if torch.cuda.is_available() else 'mps' if getattr(torch.backends, 'mps', None) and torch.backends.mps.is_available() else 'cpu'\n"
            "print(json.dumps({'python': sys.executable, 'platform': platform.platform(), 'torch': torch.__version__, 'device': device}, ensure_ascii=False))\n"
        ),
        code(
            "# 3. OPTIONAL RAMDISK\n"
            "import os, psutil, subprocess, shutil\n"
            "RAM_ROOT = Path('/content/ramdisk')\n"
            "if USE_RAMDISK:\n"
            "    mem = psutil.virtual_memory()\n"
            "    eff = min(RAMDISK_SIZE_GB, max(4, int((mem.available / (1024**3)) * 0.5)))\n"
            "    RAM_ROOT.mkdir(parents=True, exist_ok=True)\n"
            "    mounted = subprocess.run(['mountpoint', str(RAM_ROOT)], capture_output=True).returncode == 0\n"
            "    if not mounted:\n"
            "        mount_result = subprocess.run(['mount', '-t', 'tmpfs', '-o', f'size={eff}G,mode=777', 'tmpfs', str(RAM_ROOT)], text=True, capture_output=True)\n"
            "        if mount_result.returncode != 0:\n"
            "            print('RAMDISK mount failed; falling back to /content. stderr:', mount_result.stderr[-500:])\n"
            "            USE_RAMDISK = False\n"
            "    DATA_ROOT = (RAM_ROOT / 'dataset_bundle') if USE_RAMDISK else LOCAL_DATA_ROOT\n"
            "else:\n"
            "    DATA_ROOT = LOCAL_DATA_ROOT\n"
            "DATA_ROOT.mkdir(parents=True, exist_ok=True)\n"
            "LOCAL_OUTPUTS.mkdir(parents=True, exist_ok=True)\n"
            "for p in [LOCAL_CHECKPOINTS, LOCAL_EVAL, LOCAL_EXPORTS, LOCAL_LOGS]:\n"
            "    p.mkdir(parents=True, exist_ok=True)\n"
            "print('DATA_ROOT =', DATA_ROOT)\n"
        ),
        code(
            "# 4. EXTRACT DATASET BUNDLE FROM DRIVE\n"
            "import shutil, tarfile, time\n"
            "from tqdm.auto import tqdm\n\n"
            "def _safe_extract_member(tf: tarfile.TarFile, member: tarfile.TarInfo, dst: Path) -> None:\n"
            "    target = (dst / member.name).resolve()\n"
            "    root = dst.resolve()\n"
            "    try:\n"
            "        target.relative_to(root)\n"
            "    except ValueError as exc:\n"
            "        raise RuntimeError(f'Unsafe path in tar archive: {member.name!r}') from exc\n"
            "    if member.isdir():\n"
            "        target.mkdir(parents=True, exist_ok=True)\n"
            "        return\n"
            "    if not member.isfile():\n"
            "        raise RuntimeError(f'Only regular files/directories are allowed in dataset archive: {member.name!r}')\n"
            "    src_file = tf.extractfile(member)\n"
            "    if src_file is None:\n"
            "        raise RuntimeError(f'Unsafe path in tar archive: {member.name!r}')\n"
            "    target.parent.mkdir(parents=True, exist_ok=True)\n"
            "    with src_file, target.open('wb') as out_file:\n"
            "        shutil.copyfileobj(src_file, out_file, length=8 * 1024 * 1024)\n\n"
            "src = Path(DATASET_BUNDLE_DRIVE_PATH)\n"
            "if not src.exists():\n"
            "    raise FileNotFoundError(src)\n"
            "archive_local = src\n"
            "if COPY_ARCHIVE_TO_RAM_FIRST and USE_RAMDISK:\n"
            "    archive_local = RAM_ROOT / src.name\n"
            "    if archive_local.exists() and archive_local.stat().st_size == src.stat().st_size:\n"
            "        print('archive already copied:', archive_local)\n"
            "    else:\n"
            "        with src.open('rb') as fin, archive_local.open('wb') as fout:\n"
            "            total = src.stat().st_size\n"
            "            with tqdm(total=total, unit='B', unit_scale=True, desc='copy_archive') as pbar:\n"
            "                while True:\n"
            "                    chunk = fin.read(8 * 1024 * 1024)\n"
            "                    if not chunk:\n"
            "                        break\n"
            "                    fout.write(chunk)\n"
            "                    pbar.update(len(chunk))\n"
            "if DATA_ROOT.exists():\n"
            "    shutil.rmtree(DATA_ROOT)\n"
            "DATA_ROOT.mkdir(parents=True, exist_ok=True)\n"
            "with tarfile.open(archive_local, 'r:*') as tf:\n"
            "    members = tf.getmembers()\n"
            "    for m in tqdm(members, desc='extract_bundle', dynamic_ncols=True):\n"
            "        _safe_extract_member(tf, m, DATA_ROOT)\n"
            "print('bundle extracted to', DATA_ROOT)\n"
        ),
        code(
            "# 5. FETCH PROJECT FROM GIT OR ZIP (self-contained policy: no embedded repo copy in the notebook)\n"
            "import os\n"
            "import shutil\n"
            "import subprocess\n"
            "import sys\n"
            "import urllib.request\n"
            "import zipfile\n"
            "from pathlib import Path\n\n\n"
            "def _clone_repo() -> bool:\n"
            "    if not REPO_CLONE_URL:\n"
            "        return False\n"
            "    if PROJECT_ROOT.exists():\n"
            "        shutil.rmtree(PROJECT_ROOT)\n"
            "    PROJECT_ROOT.parent.mkdir(parents=True, exist_ok=True)\n"
            "    subprocess.run(\n"
            "        [\n"
            "            'git',\n"
            "            'clone',\n"
            "            '--depth',\n"
            "            '1',\n"
            "            '-b',\n"
            "            REPO_CLONE_REF,\n"
            "            REPO_CLONE_URL,\n"
            "            str(PROJECT_ROOT),\n"
            "        ],\n"
            "        check=True,\n"
            "    )\n"
            "    return True\n\n\n"
            "def _unpack_zip() -> None:\n"
            "    if not RUNTIME_ZIP_URL:\n"
            "        raise ValueError('RUNTIME_ZIP_URL is empty')\n"
            "    if PROJECT_ROOT.exists():\n"
            "        shutil.rmtree(PROJECT_ROOT)\n"
            "    zpath = Path('/tmp/unet_seam_runtime_src.zip')\n"
            "    print('downloading:', RUNTIME_ZIP_URL)\n"
            "    urllib.request.urlretrieve(RUNTIME_ZIP_URL, zpath)\n"
            "    tmp = Path('/tmp/unet_seam_src_extract')\n"
            "    if tmp.exists():\n"
            "        shutil.rmtree(tmp)\n"
            "    tmp.mkdir(parents=True)\n"
            "    with zipfile.ZipFile(zpath, 'r') as zf:\n"
            "        zf.extractall(tmp)\n"
            "    top = [p for p in tmp.iterdir() if p.is_dir()]\n"
            "    if len(top) != 1:\n"
            "        raise RuntimeError('zip must contain exactly one top-level directory, got: ' + repr([p.name for p in top]))\n"
            "    shutil.move(str(top[0]), str(PROJECT_ROOT))\n\n\n"
            "if _clone_repo():\n"
            "    pass\n"
            "elif RUNTIME_ZIP_URL:\n"
            "    _unpack_zip()\n"
            "else:\n"
            "    raise ValueError(\n"
            "        'Set REPO_CLONE_URL or RUNTIME_ZIP_URL in PARAMS. '\n"
            "        'This notebook does not embed the repository; code must come from git or a zip URL.'\n"
            "    )\n\n"
            "sys.path.insert(0, str(PROJECT_ROOT))\n"
            "_n_py = sum(1 for _ in PROJECT_ROOT.rglob('*.py'))\n"
            "print('PROJECT_ROOT =', PROJECT_ROOT, '| python files =', _n_py)\n"
        ),
        code(
            "# 6. VALIDATE BUNDLE LAYOUT\n"
            "import json\n"
            "required = [\n"
            "    DATA_ROOT / 'manifests/input_raw_manifest.jsonl',\n"
            "]\n"
            "for p in required:\n"
            "    if not p.exists():\n"
            "        raise FileNotFoundError(p)\n"
            "print(json.dumps({\n"
            "    'source_manifest': str(DATA_ROOT / 'manifests/input_raw_manifest.jsonl'),\n"
            "}, ensure_ascii=False))\n"
        ),
        code(
            "# 7. BUILD RUNTIME CONFIGS (обязателен перед 10, либо 10 сам вызовет тот же скрипт, если yml нет)\n"
            "import subprocess, sys\n"
            "subprocess.check_call(\n"
            "    [sys.executable, str(PROJECT_ROOT / 'scripts' / 'write_colab_runtime_yamls.py'),\n"
            "     '--project-root', str(PROJECT_ROOT), '--data-root', str(DATA_ROOT),\n"
            "     '--train-batch-size', str(TRAIN_BATCH_SIZE), '--val-batch-size', str(VAL_BATCH_SIZE), '--train-epochs', str(TRAIN_EPOCHS),\n"
            "     '--train-num-workers', str(TRAIN_NUM_WORKERS), '--primary-checkpoint', PRIMARY_CHECKPOINT],\n"
            "    cwd=str(PROJECT_ROOT),\n"
            ")\n"
            "print('runtime configs ->', PROJECT_ROOT / 'runtime_configs')\n"
        ),
        code(
            "# 8. OPTIONAL RESUME FROM DRIVE LAST CHECKPOINT\n"
            "import shutil\n"
            "resume_path = None\n"
            "DRIVE_CKPT_DIR.mkdir(parents=True, exist_ok=True)\n"
            "drive_last = DRIVE_CKPT_DIR / 'last_harmonizer.pt'\n"
            "if drive_last.exists():\n"
            "    LOCAL_CHECKPOINTS.mkdir(parents=True, exist_ok=True)\n"
            "    local_resume = LOCAL_CHECKPOINTS / 'resume_last.pt'\n"
            "    shutil.copy2(drive_last, local_resume)\n"
            "    resume_path = local_resume\n"
            "print('resume_path =', resume_path)\n"
        ),
        code(
            "# 9. BACKGROUND SYNC TO DRIVE (eval/exports on Drive only after you run cells 11–12; checkpoints sync during train if this cell ran before 10)\n"
            "import threading, time, shutil\n"
            "if 'SYNC_STOP' in globals():\n"
            "    SYNC_STOP.set()\n"
            "SYNC_STOP = threading.Event()\n"
            "for p in [DRIVE_RUN_DIR, DRIVE_CKPT_DIR, DRIVE_EVAL_DIR, DRIVE_EXPORT_DIR, DRIVE_LOG_DIR]:\n"
            "    p.mkdir(parents=True, exist_ok=True)\n"
            "def sync_tree(src: Path, dst: Path) -> int:\n"
            "    n = 0\n"
            "    if not src.exists():\n"
            "        return 0\n"
            "    for path in src.rglob('*'):\n"
            "        if not path.is_file():\n"
            "            continue\n"
            "        if path.name.startswith('.') or path.suffix in {'.tmp', '.part'}:\n"
            "            continue\n"
            "        rel = path.relative_to(src)\n"
            "        out = dst / rel\n"
            "        tmp = out.with_name(f'.{out.name}.tmp')\n"
            "        out.parent.mkdir(parents=True, exist_ok=True)\n"
            "        if not out.exists() or out.stat().st_mtime < path.stat().st_mtime or out.stat().st_size != path.stat().st_size:\n"
            "            try:\n"
            "                shutil.copy2(path, tmp)\n"
            "                tmp.replace(out)\n"
            "                n += 1\n"
            "            except OSError as e:\n"
            "                print('sync error', path, '->', out, e, flush=True)\n"
            "    return n\n"
            "def sync_all_to_drive() -> None:\n"
            "    a = sync_tree(LOCAL_CHECKPOINTS, DRIVE_CKPT_DIR)\n"
            "    b = sync_tree(LOCAL_EVAL, DRIVE_EVAL_DIR)\n"
            "    c = sync_tree(LOCAL_EXPORTS, DRIVE_EXPORT_DIR)\n"
            "    d = sync_tree(LOCAL_LOGS, DRIVE_LOG_DIR)\n"
            "    print('sync tick: ckpt', a, 'eval', b, 'export', c, 'logs', d, '->', DRIVE_RUN_DIR, flush=True)\n"
            "def sync_loop():\n"
            "    while True:\n"
            "        sync_all_to_drive()\n"
            "        if SYNC_STOP.wait(SYNC_INTERVAL_SEC):\n"
            "            break\n"
            "sync_all_to_drive()\n"
            "sync_thread = threading.Thread(target=sync_loop, daemon=True)\n"
            "sync_thread.start()\n"
            "print('background sync started (first tick already ran)')\n"
        ),
        code(
            "# 10b. TensorBoard (можно запускать до или после TRAIN; во время блокирующей ячейки TRAIN новая ячейка Colab не стартует)\n"
            "import subprocess, sys, time, shutil\n"
            "from google.colab import output\n"
            "\n"
            "subprocess.run([sys.executable, \"-m\", \"pip\", \"install\", \"-q\", \"protobuf<5\", \"tensorboard\"], check=True)\n"
            "\n"
            "LOGDIR = PROJECT_ROOT / \"outputs\" / \"logs\" / \"tensorboard\"\n"
            "LOGDIR.mkdir(parents=True, exist_ok=True)\n"
            "subprocess.Popen(\n"
            "    [sys.executable, \"-m\", \"tensorboard.main\", \"--logdir\", str(LOGDIR), \"--port\", \"6006\", \"--bind_all\"],\n"
            "    start_new_session=True,\n"
            "    stdout=subprocess.DEVNULL,\n"
            "    stderr=subprocess.STDOUT,\n"
            ")\n"
            "time.sleep(5)\n"
            "DRIVE_TB = DRIVE_RUN_DIR / \"tensorboard\"\n"
            "DRIVE_TB.mkdir(parents=True, exist_ok=True)\n"
            "for path in LOGDIR.rglob(\"*\"):\n"
            "    if path.is_file():\n"
            "        rel = path.relative_to(LOGDIR)\n"
            "        out = DRIVE_TB / rel\n"
            "        out.parent.mkdir(parents=True, exist_ok=True)\n"
            "        try:\n"
            "            shutil.copy2(path, out)\n"
            "        except OSError:\n"
            "            pass\n"
            "print(\"LOGDIR =\", LOGDIR, \"| копия на Drive:\", DRIVE_TB)\n"
            "output.serve_kernel_port_as_window(6006, path=\"/\")\n"
            "print(\"Если встроенный просмотр серый — открой ссылку в новой вкладке.\")"
        ),
        code(
            "# 10. TRAIN\n"
            "import os, sys, subprocess, threading\n"
            "if not (PROJECT_ROOT / 'runtime_configs' / 'train.yaml').is_file():\n"
            "    print('Нет runtime_configs — запускаю scripts/write_colab_runtime_yamls.py (как в ячейке 7)…')\n"
            "    subprocess.check_call(\n"
            "        [sys.executable, str(PROJECT_ROOT / 'scripts' / 'write_colab_runtime_yamls.py'),\n"
            "         '--project-root', str(PROJECT_ROOT), '--data-root', str(DATA_ROOT),\n"
            "         '--train-batch-size', str(TRAIN_BATCH_SIZE), '--val-batch-size', str(VAL_BATCH_SIZE), '--train-epochs', str(TRAIN_EPOCHS),\n"
            "         '--train-num-workers', str(TRAIN_NUM_WORKERS), '--primary-checkpoint', PRIMARY_CHECKPOINT],\n"
            "        cwd=str(PROJECT_ROOT),\n"
            "    )\n"
            "env = os.environ.copy()\n"
            "env['PYTHONPATH'] = str(PROJECT_ROOT)\n"
            "env['PYTHONUNBUFFERED'] = '1'\n"
            "env.setdefault('PYTORCH_CUDA_ALLOC_CONF', 'expandable_segments:True')\n"
            "cmd = [sys.executable, '-u', '-m', 'scripts.train_harmonizer', '--config', str(PROJECT_ROOT / 'runtime_configs/train.yaml')]\n"
            "resume = globals().get('resume_path')\n"
            "if resume is not None:\n"
            "    cmd += ['--resume', str(resume)]\n"
            "print('TRAIN CMD:', ' '.join(map(str, cmd)))\n"
            "print('Дальше: loading, train_start, epoch_begin, train_iter_begin (затем пауза до первого train_step — нормально: 1-й батч + воркеры + GPU).')\n"
            "def _stream_cmd(cmd, cwd, env):\n"
            "    # Colab: inherited stdio often shows nothing; PIPE + a thread that prints to the cell is reliable. Main thread only p.wait() (not read()).\n"
            "    p = subprocess.Popen(\n"
            "        cmd, cwd=cwd, env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1,\n"
            "    )\n"
            "    def _pump():\n"
            "        if p.stdout is not None:\n"
            "            for line in p.stdout:\n"
            "                print(line, end='', flush=True)\n"
            "    t = threading.Thread(target=_pump, daemon=True)\n"
            "    t.start()\n"
            "    rc = p.wait()\n"
            "    t.join(timeout=30)\n"
            "    if rc != 0:\n"
            "        print(f'\\n[exit {rc}] Причина — в Traceback/ошибке ВЫШЕ. CalledProcessError — только итог.', flush=True)\n"
            "        raise subprocess.CalledProcessError(rc, cmd)\n"
            "_stream_cmd(cmd, str(PROJECT_ROOT), env)\n"
        ),
        code(
            "# 11. EVAL\n"
            "import os, sys, subprocess\n"
            "if '_stream_cmd' not in globals():\n"
            "    import threading\n"
            "    def _stream_cmd(cmd, cwd, env):\n"
            "        p = subprocess.Popen(\n"
            "            cmd, cwd=cwd, env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1,\n"
            "        )\n"
            "        def _pump():\n"
            "            if p.stdout is not None:\n"
            "                for line in p.stdout:\n"
            "                    print(line, end='', flush=True)\n"
            "        t = threading.Thread(target=_pump, daemon=True)\n"
            "        t.start()\n"
            "        rc = p.wait()\n"
            "        t.join(timeout=30)\n"
            "        if rc != 0:\n"
            "            print(f'\\n[exit {rc}] See Traceback above.', flush=True)\n"
            "            raise subprocess.CalledProcessError(rc, cmd)\n"
            "env = os.environ.copy()\n"
            "env['PYTHONPATH'] = str(PROJECT_ROOT)\n"
            "env['PYTHONUNBUFFERED'] = '1'\n"
            "cmd = [sys.executable, '-u', '-m', 'scripts.run_eval_harmonizer', '--config', str(PROJECT_ROOT / 'runtime_configs/eval.yaml')]\n"
            "print('EVAL CMD:', ' '.join(map(str, cmd)))\n"
            "_stream_cmd(cmd, str(PROJECT_ROOT), env)\n"
        ),
        code(
            "# 12. EXPORT + VERIFY\n"
            "import os, sys, subprocess\n"
            "if '_stream_cmd' not in globals():\n"
            "    import threading\n"
            "    def _stream_cmd(cmd, cwd, env):\n"
            "        p = subprocess.Popen(\n"
            "            cmd, cwd=cwd, env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1,\n"
            "        )\n"
            "        def _pump():\n"
            "            if p.stdout is not None:\n"
            "                for line in p.stdout:\n"
            "                    print(line, end='', flush=True)\n"
            "        t = threading.Thread(target=_pump, daemon=True)\n"
            "        t.start()\n"
            "        rc = p.wait()\n"
            "        t.join(timeout=30)\n"
            "        if rc != 0:\n"
            "            print(f'\\n[exit {rc}] See Traceback above.', flush=True)\n"
            "            raise subprocess.CalledProcessError(rc, cmd)\n"
            "env = os.environ.copy()\n"
            "env['PYTHONPATH'] = str(PROJECT_ROOT)\n"
            "env['PYTHONUNBUFFERED'] = '1'\n"
            "export_cmd = [sys.executable, '-u', '-m', 'scripts.export_harmonizer_safetensors', '--config', str(PROJECT_ROOT / 'runtime_configs/export.yaml')]\n"
            "verify_cmd = [sys.executable, '-u', '-m', 'scripts.verify_harmonizer_export', '--config', str(PROJECT_ROOT / 'runtime_configs/export.yaml')]\n"
            "print('EXPORT CMD:', ' '.join(map(str, export_cmd)))\n"
            "_stream_cmd(export_cmd, str(PROJECT_ROOT), env)\n"
            "print('VERIFY CMD:', ' '.join(map(str, verify_cmd)))\n"
            "_stream_cmd(verify_cmd, str(PROJECT_ROOT), env)\n"
        ),
        code(
            "# 13. FINAL SYNC + SUMMARY\n"
            "if 'SYNC_STOP' in globals():\n"
            "    SYNC_STOP.set()\n"
            "if 'sync_all_to_drive' in globals():\n"
            "    sync_all_to_drive()\n"
            "else:\n"
            "    print('background sync was not started; skipping final sync')\n"
            "print('Drive checkpoint files:', sorted(p.name for p in DRIVE_CKPT_DIR.glob('*')))\n"
            "print('Drive export files:', sorted(p.name for p in DRIVE_EXPORT_DIR.glob('*')))\n"
            "print('Drive eval runs:', sorted(p.name for p in DRIVE_EVAL_DIR.glob('*')))\n"
        ),
    ]
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.10"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(build_notebook(), ensure_ascii=False, indent=2), encoding="utf-8")
    print(OUT)


if __name__ == "__main__":
    main()
